### ISSUE TITLE
Running recall@1 for baseline KeyError: 'generated_dependency'

### ISSUE THREAD

**Issue by pldlgb** [seketeam/EvoCodeBench#8]
Running recall@1 for baseline post-codeqwen
TODO Completions: 201

100%|███████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [17:38<00:00,  5.27s/it]
Traceback (most recent call last):
  File "/mnt/intern/QwenEval/EvoCodeBench/parser/recall_k.py", line 229, in <module>
    main()
  File "/mnt/intern/QwenEval/EvoCodeBench/parser/recall_k.py", line 225, in main
    report_results(args, k_list, output_data, benchmark_data)
  File "/mnt/intern/QwenEval/EvoCodeBench/parser/recall_k.py", line 56, in report_results
    parse_results[namespace][completion] = js['generated_dependency']
KeyError: 'generated_dependency'

**Comment by EvensXia** [comment]
same as you
